// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/oulabla/ai_app_netlog/internal/datastruct"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockService
func (_mock *MockService) Create(ctx context.Context, netlog *datastruct.Netlog) (int64, error) {
	ret := _mock.Called(ctx, netlog)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *datastruct.Netlog) (int64, error)); ok {
		return returnFunc(ctx, netlog)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *datastruct.Netlog) int64); ok {
		r0 = returnFunc(ctx, netlog)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *datastruct.Netlog) error); ok {
		r1 = returnFunc(ctx, netlog)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - netlog *datastruct.Netlog
func (_e *MockService_Expecter) Create(ctx interface{}, netlog interface{}) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, netlog)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, netlog *datastruct.Netlog)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *datastruct.Netlog
		if args[1] != nil {
			arg1 = args[1].(*datastruct.Netlog)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Create_Call) Return(n int64, err error) *MockService_Create_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(ctx context.Context, netlog *datastruct.Netlog) (int64, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockService
func (_mock *MockService) GetByID(ctx context.Context, id int64) (*datastruct.Netlog, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *datastruct.Netlog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*datastruct.Netlog, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *datastruct.Netlog); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*datastruct.Netlog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockService_Expecter) GetByID(ctx interface{}, id interface{}) *MockService_GetByID_Call {
	return &MockService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockService_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetByID_Call) Return(netlog *datastruct.Netlog, err error) *MockService_GetByID_Call {
	_c.Call.Return(netlog, err)
	return _c
}

func (_c *MockService_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*datastruct.Netlog, error)) *MockService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetList provides a mock function for the type MockService
func (_mock *MockService) GetList(ctx context.Context, filter *datastruct.NetlogFilter) ([]*datastruct.Netlog, int64, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetList")
	}

	var r0 []*datastruct.Netlog
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *datastruct.NetlogFilter) ([]*datastruct.Netlog, int64, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *datastruct.NetlogFilter) []*datastruct.Netlog); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*datastruct.Netlog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *datastruct.NetlogFilter) int64); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *datastruct.NetlogFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockService_GetList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetList'
type MockService_GetList_Call struct {
	*mock.Call
}

// GetList is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *datastruct.NetlogFilter
func (_e *MockService_Expecter) GetList(ctx interface{}, filter interface{}) *MockService_GetList_Call {
	return &MockService_GetList_Call{Call: _e.mock.On("GetList", ctx, filter)}
}

func (_c *MockService_GetList_Call) Run(run func(ctx context.Context, filter *datastruct.NetlogFilter)) *MockService_GetList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *datastruct.NetlogFilter
		if args[1] != nil {
			arg1 = args[1].(*datastruct.NetlogFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetList_Call) Return(netlogs []*datastruct.Netlog, n int64, err error) *MockService_GetList_Call {
	_c.Call.Return(netlogs, n, err)
	return _c
}

func (_c *MockService_GetList_Call) RunAndReturn(run func(ctx context.Context, filter *datastruct.NetlogFilter) ([]*datastruct.Netlog, int64, error)) *MockService_GetList_Call {
	_c.Call.Return(run)
	return _c
}
